apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: flask-backend
    project: test
data:
  MYSQL_DBNAME: app_db
  MYSQL_USER: db_user
  MYSQL_PASSWORD: db_user_pass
  MYSQL_HOST: mysql-service