apiVersion: v1
kind: Service # Create service
metadata:
  name: mysql-service # Sets the service name
  labels:
    app: mysql # Defines app to create service for
    project: test
spec:
  type: ClusterIP # Sets the service type
  selector:
    app: mysql
  ports:
    - port: 3306 # Sets the port to run the postgres application