apiVersion: apps/v1
kind: Deployment
metadata:
 name: mysql-deployment
 labels:
    project: test
spec:
 replicas: 1
 selector:
    matchLabels:
      app: mysql
 template:
    metadata:
      labels:
        app: mysql
        role: db
    spec:
      containers:
        - name: mysql
          image: mysql:8.3
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: mysql-config
            - secretRef:
                name: mysql-secret
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysqldata
      volumes:
        - name: mysqldata
          persistentVolumeClaim:
            claimName: mysql-volume-claim