apiVersion: v1
kind: Service # Create service
metadata:
  name: phpmyadmin-service # Sets the service name
  labels:
    app: phpmyadmin # Defines app to create service for
    project: test
spec:
  type: ClusterIP
  selector:
    app: phpmyadmin
  ports:
  - port: 80
    name: http
    targetPort: 80